version: '3.8'

services:
  php:
    build: .
    ports:
      - "9080:80"
    volumes:
      - .:/var/www/html   
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=user_password
    depends_on:
      - db

volumes:
  db_data:
